tunnel: ac1f6788-4491-4241-988f-fe9bfa10f0bc
credentials-file: C:\Users\Nitis\.cloudflared\ac1f6788-4491-4241-988f-fe9bfa10f0bc.json

ingress:
  - hostname: mail.edushield1.in
    service: http://localhost:3000

  - hostname: api.edushield1.in
    service: http://localhost:8000

  - service: http_status:404